//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTRL.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int initial_hours {
            get {
                return ((int)(this["initial_hours"]));
            }
            set {
                this["initial_hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int initial_minutes {
            get {
                return ((int)(this["initial_minutes"]));
            }
            set {
                this["initial_minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int goal_hours {
            get {
                return ((int)(this["goal_hours"]));
            }
            set {
                this["goal_hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int goal_minutes {
            get {
                return ((int)(this["goal_minutes"]));
            }
            set {
                this["goal_minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int goal_days {
            get {
                return ((int)(this["goal_days"]));
            }
            set {
                this["goal_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool initialized {
            get {
                return ((bool)(this["initialized"]));
            }
            set {
                this["initialized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int current_hours {
            get {
                return ((int)(this["current_hours"]));
            }
            set {
                this["current_hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int current_minutes {
            get {
                return ((int)(this["current_minutes"]));
            }
            set {
                this["current_minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int daily_subtraction_minutes {
            get {
                return ((int)(this["daily_subtraction_minutes"]));
            }
            set {
                this["daily_subtraction_minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string current_date {
            get {
                return ((string)(this["current_date"]));
            }
            set {
                this["current_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int current_seconds {
            get {
                return ((int)(this["current_seconds"]));
            }
            set {
                this["current_seconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection blocked_websites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["blocked_websites"]));
            }
            set {
                this["blocked_websites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection blocked_programs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["blocked_programs"]));
            }
            set {
                this["blocked_programs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int original_goal_days {
            get {
                return ((int)(this["original_goal_days"]));
            }
            set {
                this["original_goal_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int hours_productive {
            get {
                return ((int)(this["hours_productive"]));
            }
            set {
                this["hours_productive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int minutes_productive {
            get {
                return ((int)(this["minutes_productive"]));
            }
            set {
                this["minutes_productive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int seconds_productive {
            get {
                return ((int)(this["seconds_productive"]));
            }
            set {
                this["seconds_productive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection tommorow_blocked_websites {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tommorow_blocked_websites"]));
            }
            set {
                this["tommorow_blocked_websites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection tommorow_blocked_programs {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["tommorow_blocked_programs"]));
            }
            set {
                this["tommorow_blocked_programs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int daily_max_hours {
            get {
                return ((int)(this["daily_max_hours"]));
            }
            set {
                this["daily_max_hours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int daily_max_minutes {
            get {
                return ((int)(this["daily_max_minutes"]));
            }
            set {
                this["daily_max_minutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection leisure_last_seven_days {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["leisure_last_seven_days"]));
            }
            set {
                this["leisure_last_seven_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection productivity_last_seven_days {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["productivity_last_seven_days"]));
            }
            set {
                this["productivity_last_seven_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int total_days {
            get {
                return ((int)(this["total_days"]));
            }
            set {
                this["total_days"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int total_leisure_time {
            get {
                return ((int)(this["total_leisure_time"]));
            }
            set {
                this["total_leisure_time"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int total_productive_time {
            get {
                return ((int)(this["total_productive_time"]));
            }
            set {
                this["total_productive_time"] = value;
            }
        }
    }
}
